[package]
name = "fica"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { version = "0.3.47", features = [
	"local-offset",
	"formatting",
	"macros",
] }
infica = { path = "../", version = "0.1", features = ["local-offset"] }
owo-colors = "4.0.0"
